export const ADD_FORMS = 'ADD_FORMS';
export const FORMS_LOADING = 'FORMS_LOADING';
export const FORMS_FAILED = 'FORMS_FAILED';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const SCHEDULE_LOADING = 'SCHEDULE_LOADING';
export const SCHEDULE_FAILED = 'SCHEDULE_FAILED';
