import React, { Component } from 'react';
import Home from './HomeComponent';
import Approach from './ApproachComponent';
import Fees from './ScheduleComponent';
import Forms from './FormsComponent';
import Contact from './ContactComponent';
import Footer from './FooterComponent';
import { Switch, Route, withRouter } from 'react-router-dom';
import { connect } from 'react-redux';
import { actions } from 'react-redux-form';
